global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "fastapi-backend"
      static_configs:
          - targets: ["backend:5000"]

    - job_name: "celery"
      static_configs:
          - targets: ["celery-exporter:9808"]
