name: Build + ESLint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "latest"

            - name: Install dependencies
              run: bun install
              working-directory: frontend

            - name: Build
              run: bun run build
              working-directory: frontend

            - name: Save node_modules
              uses: actions/cache@v3
              with:
                  path: frontend/node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

    lint:
        name: ESLint
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Restore node_modules
              uses: actions/cache@v3
              with:
                  path: frontend/node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/frontend/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "latest"

            - name: Run ESLint
              run: bun run eslint
              working-directory: frontend
